import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" >
          <main className="w-screen dark:bg-black bg-white flex justify-center">
            <div className="w-screen px-4 md:w-4/5 min-h-screen">
              {children}
            </div>
          </main>
          <Toaster />
        </ ThemeProvider>
      </body>
    </html >
  );
}
